spring:
  profiles:
    active:
    - debug
---
spring:
  profiles: debug
  application:
    name: microservicecloud-config-atguigu-debug
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-atguigu-test

#请保存utf-8格式

